<!DOCTYPE html>
<html>
<head>
    <title>Hyloship INVOICE</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .title {
            font-size: 24px;
            margin-bottom: 10px;
        }
        .content {
            margin-bottom: 30px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
        }
        th, td {
            border: 1px solid #dddddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
        }
        .footer {
            text-align: center;
            font-style: italic;
            color: #888888;
        }
    </style>
</head>
<body>
    <div class="header">
        <img src="{{ asset('public/uploads/' . $general_setting->logo) }}" alt="hyloship Logo"
                            class="img-responsive logo" style="margin-top:-8px !important;width:39px;">
                           
        <div class="title">Remittance</div>
        <div class="subtitle">Remittance id# {{$remittance->id}}<br>Paid ON :{{$remittance->created_at}}
           
        </div>
    </div>
    <div class="content">
        <div class="card-body">

            <div class="table-responsive">
                <table class="table table-striped table-hover dataTable js-exportable">
                    <thead>

                        <tr>
                            <th>Shipment id</th>
                            <th>Shipment Date</th>
                            <th>Order id</th>
                            <th>Courier Name</th>
                            <th>AWB</th>
                            <th>Amount</th>
                            <th>Delivery date</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($orders as $order)
                        <tr>
                            <td>{{$order->id}}</td>
                            <td>{{$order->shipped_date}}</td>
                            <td>{{$order->vendor_order_id}}</td>
                            <td>{{ @$couriers[$order->ship_courier_id]['name'] }}</td>
                            <td>{{$order->tracking_info}}</td>
                            <td>{{$order->cod_amount}}</td>
                            <td>{{$order->delivered_date}}</td>
                        </tr>
                        @endforeach
                        
                      
                    </tbody>
                </table>
            </div><br>

        </div>
    </div>
    <div class="footer">
        Generated by Hyloship on {{ date('Y-m-d H:i:s') }}
    </div>
</body>
</html>
