<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Archive_order extends Model
{
    use HasFactory;

    // The table associated with the model.
    protected $table = 'archive_orders';

    // The primary key associated with the table.
    protected $primaryKey = 'id';

    // Indicates if the model should be timestamped.
    public $timestamps = true;

    // The attributes that are mass assignable.
    protected $fillable = [
        'user_id',
        'order_id',
        'tracking_info',
        'remittance_id',
        'cod_amount',
        'cod_status',
        'cod_date',
        'vendor_order_id',
        'shopify_order_id',
        'channel_id',
        'channel',
        'fulfillment_status',
        'fulfillment_time',
        'ship_fname',
        'ship_lname',
        'ship_email',
        'ship_company',
        'ship_phone',
        'ship_address',
        'ship_address_2',
        'ship_country',
        'ship_city',
        'ship_state',
        'ship_pincode',
        'ship_latitude',
        'ship_longitude',
        'ship_gstin',
        'same_add',
        'bill_fname',
        'bill_lname',
        'bill_company',
        'bill_phone',
        'bill_address',
        'bill_address_2',
        'bill_country',
        'bill_pincode',
        'bill_city',
        'bill_state',
        'bill_latitude',
        'bill_longitude',
        'bill_gstin',
        'e_bill_no',
        'warehouse_id',
        'return_warehouse_id',
        'weight',
        'length',
        'breadth',
        'height',
        'discount',
        'shipping_cost',
        'total',
        'custom_total',
        'note',
        'tags',
        'payment_mode',
        'status',
        'ndr_action',
        'ndr_action_date',
        'shipped_date',
        'picked_date',
        'manifest_date',
        'ship_courier_id',
        'rev_ship_courier_id',
        'shipping_courier_cost',
        'rev_shipping_courier_cost',
        'shipping_courier_type',
        'shipping_courier_weight_used',
        'shipping_courier_weight',
        'shipment_id',
        'extra_weight',
        'extra_weight_cost',
        'extracostwithoutgst',
        'extracostgst',
        'extra_weight_status',
        'extra_weight_added_by',
        'extra_weight_added_on',
        'extra_weight_closed_on',
        'extra_weght_rto_deduct',
        'cod',
        'gst',
        'gst_freight',
        'gst_cod',
        'freight',
        'codrefunded',
        'rto_charge',
        'rto_charge_gst',
        'rto_charge_witoutgst',
        'rtocharge_applied',
        'reverse_charge',
        'rate',
        'rateadd',
        'zone',
        'rev_zone',
        'manifest_id',
        'manifestprod_id',
        'total_attempt',
        'rev_tracking_info',
        'on_hold_date',
        'cancel_date',
        'rto_date',
        'rto_received_date',
        'return_date',
        'delivered_date',
        'reverse_order',
    ];

    protected $casts = [
        'cod_date' => 'datetime',
        'fulfillment_time' => 'datetime',
        'shipped_date' => 'datetime',
        'picked_date' => 'datetime',
        'manifest_date' => 'datetime',
        'extra_weight_added_on' => 'datetime',
        'extra_weight_closed_on' => 'datetime',
        'on_hold_date' => 'datetime',
        'cancel_date' => 'datetime',
        'rto_date' => 'datetime',
        'rto_received_date' => 'datetime',
        'return_date' => 'datetime',
        'delivered_date' => 'datetime',
        'status_date' => 'datetime',
        'chk_date' => 'datetime',
    ];
}
